### ISSUE TITLE
[aleph init] Consider using virtualenv and pip as packages instead of calling them in subprocesses

### ISSUE THREAD

**Issue by nkashy1** [doc-ai/aleph#3]
Currently, we assume that users have `virtualenv` and `pip` installed on their systems (and we are surely making assumptions about versions, etc.).

A more elegant approach would be to define `virtualenv` and `pip` as `aleph` requirements (in `requirements.txt`) and use them as packages. So we would use [`virtualenv.create_environment`](http://jelly.codes/articles/python-virtualenv-from-within-python/) and [`pip.main`](https://stackoverflow.com/questions/12332975/installing-python-module-within-code) instead of the subprocess calls we are currently making.

This would also make the code more readily testable/debuggable.

**Comment by phildow** [comment]
Cool. Those changes make sense.

I also think aleph should generate a requirements.txt file for the project that could be used to manage the project's environment. As I mentioned in the other issue, I'm not sure how best to handle the fact that there are two environments here, one for running the aleph cli and the other for the project itself. I'm going to look into what rails and django do here.

**Comment by phildow** [comment]
Closing given https://github.com/doc-ai/aleph/pull/5
